# Generated by Django 4.0.2 on 2022-02-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_register_country_register_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
