# Generated by Django 4.0.2 on 2022-03-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_register_created_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
