# Generated by Django 4.0.2 on 2022-03-01 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.BigIntegerField()),
                ('country', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('email_verification', models.BooleanField()),
                ('sms_verification', models.BooleanField()),
                ('status_2FA', models.BooleanField()),
                ('verification_2FA', models.BooleanField()),
                ('total_deposit_count', models.IntegerField(default=0)),
                ('total_withdraw_count', models.IntegerField(default=0)),
                ('total_transaction', models.IntegerField(default=0)),
                ('created_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
