# Generated by Django 4.0.2 on 2022-03-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo_extension')),
                ('extension_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
