# Generated by Django 4.0.1 on 2022-02-15 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('attachments', models.ImageField(upload_to='pics')),
                ('created_datetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
