# Generated by Django 4.0.2 on 2022-02-24 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_register_created_datetime'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='username',
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.register'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='detail',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='post_balance',
            field=models.FloatField(),
        ),
    ]
