# Generated by Django 4.0.2 on 2022-02-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiatcurrency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatcurrency',
            name='fiat_status',
        ),
        migrations.AlterField(
            model_name='fiatcurrency',
            name='fiat_rate',
            field=models.FloatField(),
        ),
    ]
