# Generated by Django 4.0.1 on 2022-02-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=50)),
                ('seller', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=20)),
                ('amount', models.BigIntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('exchange_rate', models.BigIntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
