# Generated by Django 4.0.2 on 2022-03-01 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traderequest', '0002_remove_traderequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='exchange_rate',
            field=models.IntegerField(),
        ),
    ]
