# Generated by Django 4.0.1 on 2022-02-14 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_name', models.CharField(max_length=50)),
                ('crypto_image', models.ImageField(upload_to='pics')),
                ('crypto_code', models.CharField(max_length=20)),
                ('crypto_symbol', models.CharField(max_length=20)),
                ('crypto_rate', models.IntegerField()),
                ('crypto_status', models.CharField(max_length=20)),
                ('createddatetime', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
