# Generated by Django 4.0.2 on 2022-02-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='crypto_image',
            field=models.ImageField(upload_to='crypto_pics'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='crypto_status',
            field=models.BooleanField(default=False),
        ),
    ]
