# Generated by Django 4.0.2 on 2022-02-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrency', '0002_alter_cryptocurrency_crypto_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='crypto_status',
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='crypto_rate',
            field=models.FloatField(),
        ),
    ]
